<!DOCTYPE HTML>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ToDoチェッカー</title>
    <link rel="stylesheet" href="/css/index.css" media="all" type="text/css" >
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css" >
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="/js/search.js"></script>
</head>
<body>
    <header id="header">
        <a href="/" class="ttl"><h1>ToDoチェッカー</h1></a>
        <p class="search_link">
            <a href="/search/">検索</a>
        </p>
    </header>
    <div id="wrapper">
        <div id="addlist" class="clearfix">
            <form method="post" id="searchForm">
            <?= $this->searchForm->name ?>
            <?//= $this->searchForm->period ?>
            <p class="btn">
                <button>検索</button>
            </p>
            </form>
        </div>
        <div id="result"></div>
    </div>
    <footer id="footer">
        ToDoチェッカー
    </footer>
</body>
</html>
